export { ReactComponent as ChevronDown } from './chevron-down.svg'
export { ReactComponent as FileIcon } from './file-icon.svg'
export { ReactComponent as NavbarSearchIcon } from './navbar-search-icon.svg'
export { ReactComponent as AccountTackover } from './account-tackover.svg'
export { ReactComponent as CardingFraud } from './carding-fraud.svg'
