export { ReactComponent as ChevronDown } from './chevron-down.svg'
export { ReactComponent as FileIcon } from './file-icon.svg'
export { ReactComponent as NavbarSearchIcon } from './navbar-search-icon.svg'
// nav icon
export { ReactComponent as ActiveBotProtection } from './active-bot-protection.svg'
export { ReactComponent as BotAttackIntel } from './bot-attack-intel.svg'
export { ReactComponent as BussinessLoginIcon } from './bussiness-login-icon.svg'
export { ReactComponent as AccountTackover } from './account-tackover.svg'
export { ReactComponent as CardingFraud } from './carding-fraud.svg'
export { ReactComponent as CredentialStuffing } from './credential-stuffing.svg'
export { ReactComponent as MarketingAnalytics } from './marketing-analytics.svg'
export { ReactComponent as ScaperIcon } from './scaper-icon.svg'
