export const mocks = {
  featuredCards: [
    {
      heading: "Account takeover",
      _type: "featuredCardsObject",
      icon: {
        extension: "svg",
        _createdAt: "2024-01-25T13:56:43Z",
        url:
          "https://cdn.sanity.io/images/uiptp553/production/ffa4370a99f6615c053ffa4eddce76c548d516ff-48x49.svg",
        _type: "sanity.imageAsset",
        _updatedAt: "2024-01-25T13:56:43Z",
        uploadId: "wcxZbPS6NmFZgeECgz9Hp83xJ1pKkFjj",
        mimeType: "image/svg+xml",
        path:
          "images/uiptp553/production/ffa4370a99f6615c053ffa4eddce76c548d516ff-48x49.svg",
        sha1hash: "ffa4370a99f6615c053ffa4eddce76c548d516ff",
        assetId: "ffa4370a99f6615c053ffa4eddce76c548d516ff",
        _id: "image-ffa4370a99f6615c053ffa4eddce76c548d516ff-48x49-svg",
        _rev: "GspWPjs815p7KTxv21KmVQ",
        metadata: {
          blurHash: "ej2HbLflawfmkbfmfPf5fRfQflfQkZfPacfjfRflf6fPkvfRacfPf4",
          _type: "sanity.imageMetadata",
          palette: {
            lightVibrant: {
              foreground: "#000",
              title: "#fff",
              population: 0,
              background: "#98a8e1",
              _type: "sanity.imagePaletteSwatch",
            },
            darkVibrant: {
              title: "#fff",
              population: 0.13,
              background: "#063981",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
            },
            lightMuted: {
              foreground: "#fff",
              title: "#fff",
              population: 0,
              background: "#223576",
              _type: "sanity.imagePaletteSwatch",
            },
            vibrant: {
              background: "#3857c1",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.38,
            },
            dominant: {
              foreground: "#fff",
              title: "#fff",
              population: 0.38,
              background: "#3857c1",
              _type: "sanity.imagePaletteSwatch",
            },
            _type: "sanity.imagePalette",
            darkMuted: {
              background: "#2c3c4e",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.13,
            },
            muted: {
              background: "#5564a4",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.34,
            },
          },
          hasAlpha: true,
          lqip:
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAACLUlEQVQ4jZ2UzU8UQRDFe4mgROMSxQOf80ZQomjAj6jxM9F40AHUkOhB7yTuvsY/2wvJvEEiCRdTPTWzGJfAenjZ3u6pX7/qruoA6huol6DugloFdWdErXqsMb4GUJ9AzWXUeVCTrgtn1KTJY+eMZcANUF1QAT3Z/9HUa8fG2Ag5VYCaymNlk51TAMPWOx47lUcVAawKxKoL2mTVQVTIYpk0CCoD+iYlZSaWIaNCbjEWWzMMmBx28+iLUWH282GYr4FjoC6BmgZ11cfjWVTHNlyMCojmsE25CHmsipxVF81ivwzXzQ01DmoW1DqoJ8e0ZhskaJMyKzPTNVYLTOeQdq5CFpOzGVCPQT0D9RTUK6+IL6BWMmqsAaLObjgwnWFdDlZjj0DdA/UG1DtQr0E9B5WB1bn63JVSHg4c3OIUqAegboG67aW15UUMUEt+nqG55dOAl0E9dOi6X1zh52eO7/s34WSg2/ePJjzlj+7srWvL52xtAm7iBIf1bovcT/UF6ppfxCaoF65Nn5vO+/sh6x+lUhsKtN3yxuGgBq+AuumprvnY5sawW4baRPX3LbeF7Z2y0PZmGbLeYVOPF13jczwIed8AZVjmnkGb1qsLG1EFogNj1VnarcLCzl4C5t+P/unnmf7v9Luy8zPM/zioHQ4eh8KsDrvlUdTxGm5TtoO2ugvL/DXy87Uc2xhjbNpgG9QNb357BJqH4Cw6/r0xthvgB1Dvvb3+RxZrjO0/quR7xS3u6SoAAAAASUVORK5CYII=",
          dimensions: {
            _type: "sanity.imageDimensions",
            width: 48,
            aspectRatio: 0.9795918367346939,
            height: 49,
          },
          isOpaque: false,
        },
        originalFilename: "AT.svg",
        size: 1692,
      },
      _key: "cb9a45cc6343",
      subText: [
        {
          markDefs: [],
          children: [
            {
              marks: [],
              text:
                "Stop malicious actors from seizing control of customer accounts.",
              _key: "9a5ab0bab3fc0",
              _type: "span",
            },
          ],
          _type: "block",
          style: "normal",
          _key: "e53ceadfe801",
        },
      ],
      button: {
        externalLink: false,
        _type: "button",
        variant: "text-link-arrow",
        label: "Stop Account Takeover Attacks",
        slug: {
          _type: "slug",
          current: "/",
        },
        mode: "light",
      },
    },
    {
      button: {
        label: "Stop Carding Attacks",
        slug: {
          current: "/",
          _type: "slug",
        },
        mode: "light",
        externalLink: false,
        _type: "button",
        variant: "text-link-arrow",
      },
      heading: "Carding fraud",
      _type: "featuredCardsObject",
      icon: {
        _createdAt: "2024-01-25T13:57:58Z",
        url:
          "https://cdn.sanity.io/images/uiptp553/production/5e8dbbf454f6ca91a89661da924349ade67adc0f-48x49.svg",
        size: 948,
        extension: "svg",
        uploadId: "EirUi1IJaQyfTmzq4plrUbdCjZdLz8fr",
        _type: "sanity.imageAsset",
        metadata: {
          hasAlpha: true,
          lqip:
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAACRElEQVQ4jZ2UXWtTQRCGJ1qrvSgnqFDbaPIupq1SvVFE6hciqGhaRHIj6I0US9NmBhGr/0eqIHgh+qf8KDbvoV5XZs+mjZBg4sVLZmdnnp3dzByB8hmUt6C8COUClBdG1ELKdcZTgfIxlJWa8iiUE0nHhtSEK+VWnOXAJSgzKAUb9PVo2ti3nbEkQdmAshwsd2dpZKCylHLLwdgQaN6A5RnUnXkpWEdq7Y5AC/k6+G+yu36PKdZ5KeYWDAfGCrNglGB+GqXWjicfCsqxYDwSNKmwx3zPY3pzUFy5IcHyRtA887KDl+/XaHMcymko52Cc/Uvu8702xz02pCsnxgCgsgzlPShXYVyB8XnSSvQVe+V/AmH+HhE4BWUbyk8wfoXxc9KX6FNupBjxnL5ARCBLKN7Dg9egfAfjBxi3YHwP40cot9LeVIw1zxlU4UHbnITyLpQPYLwC42Uob0C5DOUTKO+nGOm2Tf8KI9BbgSegvAblJRhnYLHiOpSL6f1uQjvHU2wJQwAnI0x5G8ZFGK/CeB3GOwnoFU8ODQzKwzCWYZxOFc4k23UKxizG9APuN7bmsUnPrP2WamtHTq/mIrIn599+k3Nvvsvsq205+/KXzG9uS+VFLrXWjlTXd1Nj5weNDWOjOLEYvWprV2rrHamuUSTbk/nNHzL3+meU2+7zvRjT2k2j1zsp2vdfLmQD1O/jYD6+xZW9FXwypK5+4mhfm7rt5zhj2Y0mNM6ot4r3lsvtYdQb74xmF/gIyoexkf9PnuuM5h/NXIID9A0f2gAAAABJRU5ErkJggg==",
          dimensions: {
            _type: "sanity.imageDimensions",
            width: 48,
            aspectRatio: 0.9795918367346939,
            height: 49,
          },
          isOpaque: false,
          blurHash: "el27^sflf5flkaflfQf6fQfQflfRkZfPe,flfQfRfRf6kvfPabfRf5",
          _type: "sanity.imageMetadata",
          palette: {
            dominant: {
              foreground: "#fff",
              title: "#fff",
              population: 0.64,
              background: "#4d619c",
              _type: "sanity.imagePaletteSwatch",
            },
            _type: "sanity.imagePalette",
            darkMuted: {
              background: "#28445c",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.09,
            },
            muted: {
              background: "#4d619c",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.64,
            },
            lightVibrant: {
              population: 0.09,
              background: "#346cec",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
            },
            darkVibrant: {
              background: "#041484",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.09,
            },
            lightMuted: {
              population: 0,
              background: "#0d338b",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
            },
            vibrant: {
              population: 0.38,
              background: "#146cf0",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
            },
          },
        },
        path:
          "images/uiptp553/production/5e8dbbf454f6ca91a89661da924349ade67adc0f-48x49.svg",
        _updatedAt: "2024-01-25T13:57:58Z",
        assetId: "5e8dbbf454f6ca91a89661da924349ade67adc0f",
        originalFilename: "CF.svg",
        mimeType: "image/svg+xml",
        sha1hash: "5e8dbbf454f6ca91a89661da924349ade67adc0f",
        _id: "image-5e8dbbf454f6ca91a89661da924349ade67adc0f-48x49-svg",
        _rev: "GspWPjs815p7KTxv21KsJA",
      },
      _key: "bcae9bf8bd6f",
      subText: [
        {
          markDefs: [],
          children: [
            {
              _type: "span",
              marks: [],
              text:
                "Detect and block automated card cracking, carding and enumeration attacks.",
              _key: "e2e4527081680",
            },
          ],
          _type: "block",
          style: "normal",
          _key: "ef793389257a",
        },
      ],
    },
    {
      button: {
        externalLink: false,
        _type: "button",
        variant: "text-link-arrow",
        label: "Stop Credential Stuffing Attacks",
        slug: {
          current: "/",
          _type: "slug",
        },
        mode: "light",
      },
      heading: "Credential stuffing",
      _type: "featuredCardsObject",
      icon: {
        uploadId: "JdWVofgE0RuYyvgLeV0LvYQjg6UQVdL6",
        url:
          "https://cdn.sanity.io/images/uiptp553/production/adafdfe4d5a61bb9d23c2183c4f320fdbc4ee038-48x49.svg",
        originalFilename: "square-badge.svg",
        assetId: "adafdfe4d5a61bb9d23c2183c4f320fdbc4ee038",
        _updatedAt: "2024-01-25T14:00:58Z",
        _id: "image-adafdfe4d5a61bb9d23c2183c4f320fdbc4ee038-48x49-svg",
        sha1hash: "adafdfe4d5a61bb9d23c2183c4f320fdbc4ee038",
        path:
          "images/uiptp553/production/adafdfe4d5a61bb9d23c2183c4f320fdbc4ee038-48x49.svg",
        mimeType: "image/svg+xml",
        size: 1283,
        _createdAt: "2024-01-25T14:00:58Z",
        extension: "svg",
        metadata: {
          blurHash: "ek27@kflf5fmkbfmfRf5f5fRfmfkkZf5acf4f5fmflf6kvfRabfPf5",
          _type: "sanity.imageMetadata",
          palette: {
            lightMuted: {
              foreground: "#fff",
              title: "#fff",
              population: 0,
              background: "#1d3a7b",
              _type: "sanity.imagePaletteSwatch",
            },
            vibrant: {
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.13,
              background: "#2c59bc",
            },
            dominant: {
              background: "#2c59bc",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.13,
            },
            _type: "sanity.imagePalette",
            darkMuted: {
              title: "#fff",
              population: 0.09,
              background: "#2c3050",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
            },
            muted: {
              foreground: "#fff",
              title: "#fff",
              population: 0.13,
              background: "#546199",
              _type: "sanity.imagePaletteSwatch",
            },
            lightVibrant: {
              background: "#93ade5",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#000",
              title: "#fff",
              population: 0,
            },
            darkVibrant: {
              population: 0.09,
              background: "#041c8c",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
            },
          },
          hasAlpha: true,
          lqip:
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAACGUlEQVQ4jZ2Uz2tTQRDH5ylGSyuJ1otWzXfTFNRGW62iVRDBH6CvVUoOCgp68pL3Xfwf/Ds9eVMsO68e9Cazb/NsQmtfDHxhMpn57MzuTATUd6A+BPU6qKugDmbUaso1xlsBdQfUpS71JKhzSacaas6UcpeMZcAtUNugCkZq32fTqLaNsSWOmoPacb40ZzaVkB2iiRhX5Xac11zAMocv22ApjmUGf0AVRdK032uVw1ISw4CxwrarQNXphWYotAXqPKgLUzJfK8bUFdYt5+J8mTuWbUy2bJfdB3UD1HUUupa0nnwrKUZijo/dtY11GPAMqA9AfVRDqTdAXUvjsWl31gjoqqBFMNwD9Saoy0n9NHN3wTBwDAtgaFzhYqpiI8EcqLdA3Qb1JahXHEPLDncNgdbOJhgeg+F22oinoH4A9T2o9x11fgx0RwKL0ALDRTBcA4M9wFVQX4D6GtQ3oD4B9ezRd+jtx2BAAcMxMJyoFB/pDhieVVKr+vQ/ga5yZt2JwY5gsw3eAcMFMJyPdhGOxyXwU8B6sG3a42mx5X2wIN24JbviuCs9/pCV0VfpftqTwecv4ny9etVgw2sOn4C+qnD8cXHlSukxiCv2pOe/y7L/Jpf9L4uVSx9/2+qOHzJtCv+2fMDiN1EWc62o1LLNVpz6Pn/O/PfV93WOMbbNGKbdtGE+l2R2E+2PN8ZwDHyV5uz5f8pyjTH8A8PHd8iPrqchAAAAAElFTkSuQmCC",
          dimensions: {
            _type: "sanity.imageDimensions",
            width: 48,
            aspectRatio: 0.9795918367346939,
            height: 49,
          },
          isOpaque: false,
        },
        _type: "sanity.imageAsset",
        _rev: "GspWPjs815p7KTxv21LFgi",
      },
      _key: "71b2b3b25eec",
      subText: [
        {
          _type: "block",
          style: "normal",
          _key: "9e02b7fc4090",
          markDefs: [],
          children: [
            {
              text:
                "Stop attackers from brute forcing their way into your customers' accounts.",
              _key: "ab28dc7092140",
              _type: "span",
              marks: [],
            },
          ],
        },
      ],
    },
    {
      _type: "featuredCardsObject",
      icon: {
        url:
          "https://cdn.sanity.io/images/uiptp553/production/9d7c11943997613f1482a8f53837e510bba202ab-48x49.svg",
        _rev: "J6m3sXezoblUkfhFapE8hw",
        mimeType: "image/svg+xml",
        uploadId: "t6rR3IU2obBv3M0ZErrATXK7ZxPz84Vh",
        metadata: {
          lqip:
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAB9klEQVQ4jZ2US2tUQRCF+5IEE3zcGJUsYpgqjCCOboKiICqID/QmisxS/8HM6aAbF/nRk9O4c6FUd01PojMh18Vharqrvqqurr5BwK8CvhDwoYBDAR/01NBjjfElCPhZwJ0BeEnADdf6BbVh8tgdYxnwQMBWwCBj2v9+GlfbGAdBwU7ATY3JFpveQLDx2E2N7IIgdRJTK7DF1AhOQlY8qUHqkjiT72cfi0nBGQbMFbYaGTRatgLUc4B6VGDmozmmHrkLGlOnSK3EZHZjjrvfp0G/ZfCaHUXA6wJedq3p0TQM4tShqcmxSK2xzgD/6uGKgLcFfOqajYjd5urcL50DtGxz4LpD3gj4WsDnPmtD3yt+kYuBin8qtNm67z02PRPwiYB3fa9WqFgE9CNrmatVmXBbwMcCHgr40avbF/CegLfcJ8zGZinQna563wz0zmX2e2+BJbp2eg51KbA4XRHwkYNeut4K+MrtfU8algLrpcR6w62C2xpTlsTcghsCbll1Cq7ookupg22NjakZ2CuZmBgG4/lw704sIfN62TdNc4yfrgy2RHYSC9Aq1OpcpD9+hTvHv8++X0+Yf1Hb5C8FC3vY/+MQ7fmWI9tY2PMKe/jZ+/O1F2uMMQ7NGPmwWsNvusy+iE77G2M0A34S8IPP2f/IYo0x+gOOCXk8IYpC5AAAAABJRU5ErkJggg==",
          dimensions: {
            _type: "sanity.imageDimensions",
            width: 48,
            aspectRatio: 0.9795918367346939,
            height: 49,
          },
          isOpaque: false,
          blurHash: "em1}PzflflflkbfkfQfRfQfRf-fQkGfQacfmfQf5fQf5kvfQabfQfk",
          _type: "sanity.imageMetadata",
          palette: {
            dominant: {
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.21,
              background: "#041585",
            },
            _type: "sanity.imagePalette",
            darkMuted: {
              background: "#2c3c49",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.13,
            },
            muted: {
              background: "#546199",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.13,
            },
            lightVibrant: {
              background: "#93a9e6",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#000",
              title: "#fff",
              population: 0,
            },
            darkVibrant: {
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.21,
              background: "#041585",
            },
            lightMuted: {
              background: "#1c367c",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0,
            },
            vibrant: {
              title: "#fff",
              population: 0.09,
              background: "#2c54c0",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
            },
          },
          hasAlpha: true,
        },
        extension: "svg",
        _updatedAt: "2024-01-25T14:04:31Z",
        size: 2071,
        originalFilename: "square-badge.svg",
        sha1hash: "9d7c11943997613f1482a8f53837e510bba202ab",
        _createdAt: "2024-01-25T14:04:31Z",
        _type: "sanity.imageAsset",
        path:
          "images/uiptp553/production/9d7c11943997613f1482a8f53837e510bba202ab-48x49.svg",
        assetId: "9d7c11943997613f1482a8f53837e510bba202ab",
        _id: "image-9d7c11943997613f1482a8f53837e510bba202ab-48x49-svg",
      },
      _key: "809d530f50cf",
      subText: [
        {
          _key: "9d553185e534",
          markDefs: [],
          children: [
            {
              text:
                "Halt attempts to create masses of accounts; damaging your business.",
              _key: "02a52282387a0",
              _type: "span",
              marks: [],
            },
          ],
          _type: "block",
          style: "normal",
        },
      ],
      button: {
        label: "Stop Fake Account Creation",
        slug: {
          current: "/",
          _type: "slug",
        },
        mode: "light",
        externalLink: false,
        _type: "button",
        variant: "text-link-arrow",
      },
      heading: "Fake account creation",
    },
    {
      icon: {
        _type: "sanity.imageAsset",
        uploadId: "ntDHtlkgEYfGR5b6XLG0R4ulhpMR7pjp",
        _updatedAt: "2024-01-25T15:16:43Z",
        _createdAt: "2024-01-25T15:16:43Z",
        mimeType: "image/svg+xml",
        sha1hash: "7ef6ad55a647d6824a6479abc7a6a542d99ff660",
        originalFilename: "square-badge.svg",
        url:
          "https://cdn.sanity.io/images/uiptp553/production/7ef6ad55a647d6824a6479abc7a6a542d99ff660-48x49.svg",
        path:
          "images/uiptp553/production/7ef6ad55a647d6824a6479abc7a6a542d99ff660-48x49.svg",
        assetId: "7ef6ad55a647d6824a6479abc7a6a542d99ff660",
        extension: "svg",
        _rev: "GspWPjs815p7KTxv21y6Zo",
        size: 1474,
        _id: "image-7ef6ad55a647d6824a6479abc7a6a542d99ff660-48x49-svg",
        metadata: {
          lqip:
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAACR0lEQVQ4jaWUX2sTQRTFZ9tGLagptOKfmuydWkVbFX1QlIr4IIimRaVSChWfxeyZVEG/nt/CLyHSnG3BtypnZhIr0tjowyWzu3N/uefOPeMMfG3gQwNvGLhs4PUxYznnirHlDHxp4HwJHjdwOseJI8a0IufOiyXgqoFNA511qefxojtci7HqPNgxcMaHWi+LsYFgkXNnfGDHGeqOhbpp0Mu6sF7fzX787nzICYFx3a7oStD5qu/KQLfQ3XUb136kHOUmhoCxwqaSfGDh3L5rbe+p8iHwUoiwyRJslGAhcIldV4a+86iL/OeS3HE+1B2Pummh1roQaPnt1whUYqva0eaGgS0Dlwyclczz77+5ha4qYxFzUTfF+g2oj5KjUGUrn/b1fTLDnhi4YeB99avd23Hu85fU98OAKl8gheSk/tVTBl418JWBbwx8auAFC/3CPvw6lEMrvLhdu3avltxG7osktg18YOCzPMjTCz268l1/OBkjJVvghIFnDLyVQXLBioH3DLxi4ClfMfbbj6ww9iPKUN/OGXjTwMdZ6paBL7IRlqxiI09CMRqYNqnCuSzvUe7fZrapDueygFb9BRjLTzImPDjnE/COgXcNvB1B4Nno4YrFAGg6vAFwONj4w3rHDDxp4On8q4tgSj32AiWYkxmy9dJgW2DHQgYG2ShWmDan05O9ctC1ewNgPGGXrHfQKUiS//tyCLJvkrymydfHReyNfX0thmGOGGtarOdma4B1sgqtjxIH94uxPgA+zy6Qrf4llCvG+k/OqXizEvRVUQAAAABJRU5ErkJggg==",
          dimensions: {
            _type: "sanity.imageDimensions",
            width: 48,
            aspectRatio: 0.9795918367346939,
            height: 49,
          },
          isOpaque: false,
          blurHash: "eh2HR]fka}f-kufPf6flflfPf-flkGf4abf-flf4f4aykvf6abflfP",
          _type: "sanity.imageMetadata",
          palette: {
            vibrant: {
              population: 0.68,
              background: "#455eb9",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
            },
            dominant: {
              background: "#4d619e",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.94,
            },
            _type: "sanity.imagePalette",
            darkMuted: {
              foreground: "#fff",
              title: "#fff",
              population: 0.09,
              background: "#305454",
              _type: "sanity.imagePaletteSwatch",
            },
            muted: {
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.94,
              background: "#4d619e",
            },
            lightVibrant: {
              foreground: "#000",
              title: "#fff",
              population: 0,
              background: "#9eabda",
              _type: "sanity.imagePaletteSwatch",
            },
            darkVibrant: {
              foreground: "#fff",
              title: "#fff",
              population: 0.09,
              background: "#041c8c",
              _type: "sanity.imagePaletteSwatch",
            },
            lightMuted: {
              foreground: "#fff",
              title: "#fff",
              population: 0,
              background: "#29386f",
              _type: "sanity.imagePaletteSwatch",
            },
          },
          hasAlpha: true,
        },
      },
      _key: "f46455d5029b",
      subText: [
        {
          markDefs: [],
          children: [
            {
              _type: "span",
              marks: [],
              text:
                "Prevent exploitation of new account bonuses and fake account creation.",
              _key: "55a3bdff49790",
            },
          ],
          _type: "block",
          style: "normal",
          _key: "ac5c466f0472",
        },
      ],
      button: {
        mode: "light",
        externalLink: false,
        _type: "button",
        variant: "text-link-arrow",
        label: "Stop Loyalty Point Fraud",
        slug: {
          current: "/",
          _type: "slug",
        },
      },
      heading: "Loyalty point fraud",
      _type: "featuredCardsObject",
    },
    {
      icon: {
        size: 2223,
        assetId: "75e096a3bfffe5d4fff2c2258d567839ac7e4538",
        mimeType: "image/svg+xml",
        _rev: "L7VDs79nOp3hJw51jO4dqj",
        _type: "sanity.imageAsset",
        path:
          "images/uiptp553/production/75e096a3bfffe5d4fff2c2258d567839ac7e4538-48x49.svg",
        _createdAt: "2024-01-25T15:17:36Z",
        _id: "image-75e096a3bfffe5d4fff2c2258d567839ac7e4538-48x49-svg",
        originalFilename: "square-badge.svg",
        extension: "svg",
        uploadId: "IUpuZTZex7JkJfYCwS9RO66FXYrFGyxf",
        metadata: {
          lqip:
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAB5klEQVQ4jZ2UzYsTQRDFe0zUjR6yoLeg81riafWoIu7uQUExs4tILoKiB/W0vhZBD3rVP3je4B8g1VOTj/0IEw+PVHf6/aaqqO4A6h2oQ1D3Qe2Burel9txrjLcB1GtQk5K6Cmrk2umpkcm9E2MZ8AjUGFTAiWy9nU4WsTGOQqQqULsxNbZZnDIUF2jtTGy9uzGpCmBTITVj0DabIqY6RNYhJrVyo/2eiZOtmyJ7W4YBc4ZjBxTd4RwnDSJ1Ga2uuCy+lGEZmM91JVchpqaKbMZYL3kA6haofVBPI3UYqf1IHUTqUaQmkfUgV0IV5jWGsc4B1gGptkwegvoO6jeon6B+uJg/lLTTZYjNwEWG8An4DOobqK+gPoF6D+qxj0zoCxyCuu1ZvgD10TVD0hMk3fFehr7AkcPegPrgZdKze+79HbSToc3AkgplCzwAlVZ69wvUH+/rg20zHIK5rGc2CpGaxbafdk1noKZ+JmwGJhXlcr7McA3U9U6xXdsdHuJLHbJ4CrgYbObNYmVg17R6U7IcGJPdrmY52EiqkFqgZXjeA3AG5iptZpdt8pvCtuQLHoc+KrLXkvKSj+2lsD+n/Lv18zVNC48xji2Yg7oL6gaomy6L+2j1vDHmHfCVj8PL/5R5jTH/B/PEgIkgB95XAAAAAElFTkSuQmCC",
          dimensions: {
            height: 49,
            _type: "sanity.imageDimensions",
            width: 48,
            aspectRatio: 0.9795918367346939,
          },
          isOpaque: false,
          blurHash: "em27;ZflfRflkbfmfQf5fQfRf-fPkGfRacf5fQflfQf6kvfQabfPfR",
          _type: "sanity.imageMetadata",
          palette: {
            lightVibrant: {
              background: "#81adf7",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#000",
              title: "#fff",
              population: 0,
            },
            darkVibrant: {
              background: "#041684",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.13,
            },
            lightMuted: {
              population: 0,
              background: "#083b90",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
            },
            vibrant: {
              background: "#0c54cc",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.04,
            },
            dominant: {
              background: "#041684",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.13,
            },
            _type: "sanity.imagePalette",
            darkMuted: {
              foreground: "#fff",
              title: "#fff",
              population: 0.04,
              background: "#2c4c5c",
              _type: "sanity.imagePaletteSwatch",
            },
            muted: {
              background: "#645ca4",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.04,
            },
          },
          hasAlpha: true,
        },
        url:
          "https://cdn.sanity.io/images/uiptp553/production/75e096a3bfffe5d4fff2c2258d567839ac7e4538-48x49.svg",
        sha1hash: "75e096a3bfffe5d4fff2c2258d567839ac7e4538",
        _updatedAt: "2024-01-25T15:17:36Z",
      },
      _key: "6df232b802b8",
      subText: [
        {
          markDefs: [],
          children: [
            {
              _type: "span",
              marks: [],
              text:
                "Maintain the integrity of online sales and ensure goods go to real customers.",
              _key: "4bb7ae5ed7cd0",
            },
          ],
          _type: "block",
          style: "normal",
          _key: "462e6a1b3063",
        },
      ],
      button: {
        variant: "text-link-arrow",
        label: "Stop Scalper Bot Attacks",
        slug: {
          current: "/",
          _type: "slug",
        },
        mode: "light",
        externalLink: false,
        _type: "button",
      },
      heading: "Scalper bots",
      _type: "featuredCardsObject",
    },
    {
      _type: "featuredCardsObject",
      icon: {
        _id: "image-b370abe89814917bec5496aba4816caa1868133b-48x49-svg",
        uploadId: "3eAxPee52RSqQVkl1GT8Dsjhx9CFNf94",
        _createdAt: "2024-01-25T15:25:35Z",
        _updatedAt: "2024-01-25T15:25:35Z",
        metadata: {
          isOpaque: false,
          blurHash: "ei27@ifkf6fnkbfPf5flflfPf-fRkZf5e,f-flf4f4f7kvfRabf5fP",
          _type: "sanity.imageMetadata",
          palette: {
            vibrant: {
              background: "#0444a4",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.04,
            },
            dominant: {
              background: "#041c8c",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.09,
            },
            _type: "sanity.imagePalette",
            darkMuted: {
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.04,
              background: "#343c5c",
            },
            muted: {
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.04,
              background: "#545cb4",
            },
            lightVibrant: {
              _type: "sanity.imagePaletteSwatch",
              foreground: "#000",
              title: "#fff",
              population: 0,
              background: "#7db0fb",
            },
            darkVibrant: {
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.09,
              background: "#041c8c",
            },
            lightMuted: {
              foreground: "#fff",
              title: "#fff",
              population: 0,
              background: "#033d95",
              _type: "sanity.imagePaletteSwatch",
            },
          },
          hasAlpha: true,
          lqip:
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAACRElEQVQ4jZ2U3U8TURDF74JoSVQwKkEI7BmoxgQMifji9xfxqyAaHjU+m9Az8OZfbehZMfFJzeze1gohFpuc9HZ35tczc+feBOojqEegboFaAbV6Sq3k3GB8SKDeg5ovqXOgJrNaI2oylHPngxXATVBToBJ2Fb9Pp93BOhibyagOqGnzKh4WI0COxhQ5d9pcnQRWHXg1BcbDqsBeL8VnYT+Ce7XKULeXbE8J3qiMeK+SRU6zDkYAa4dT5krmKlL6WQdi/0da/vKrdrHw+TCVjbPo24WSOrvYVVps4EXk5pI7ybzqGKupGsKqMA8n4awuI5X83i+tlXd1A1S7pMbr594AgxGsv4DhEPyalvxgCBgl6TwoA/UK1CdQt0FN/OmhjgMb25F8kNCtS+2XOAdqDdQDUM/yvJXoO2SzKceBeVPK7re+q4ugboK6C+o+qMegXoJ6Agqgzgx23U8Eqii7VWxA/PtsLi1gT0FtwbUN1wt4fTJa9Y7zH0B066Doz5xRd6zp21uj3plrA657cK3CNZlHqDgRaNEPRoPVMuqGUc+N2jbqobFaN6/W4VqDqw3PDn004IRRM0aZUctGXTNWV82rWbhm4LpkrvEA2lHgYLCHgPBeaMyoMetW4wgxyzVWv6vd9WpgPnrNYMPVgTdAeFUYewFOzXcvLTWOw0Gt/tFrgMqjNnxS2J/DkS+HY5eFRW6YyiVvxU0RL9s8PPX11fZBTjC2YrED6jqoy6CuZMV6FA3HB2OnD9wG9QbU6/9U5AZj5zceJHfP9C1FeAAAAABJRU5ErkJggg==",
          dimensions: {
            _type: "sanity.imageDimensions",
            width: 48,
            aspectRatio: 0.9795918367346939,
            height: 49,
          },
        },
        _rev: "GspWPjs815p7KTxv2223oC",
        url:
          "https://cdn.sanity.io/images/uiptp553/production/b370abe89814917bec5496aba4816caa1868133b-48x49.svg",
        originalFilename: "square-badge.svg",
        _type: "sanity.imageAsset",
        mimeType: "image/svg+xml",
        path:
          "images/uiptp553/production/b370abe89814917bec5496aba4816caa1868133b-48x49.svg",
        sha1hash: "b370abe89814917bec5496aba4816caa1868133b",
        size: 1122,
        extension: "svg",
        assetId: "b370abe89814917bec5496aba4816caa1868133b",
      },
      _key: "dcea083d5244",
      subText: [
        {
          markDefs: [],
          children: [
            {
              _type: "span",
              marks: [],
              text:
                "Prevent bots from stealing your marketing budget and skewing your analytics.",
              _key: "2b2efa216bd90",
            },
          ],
          _type: "block",
          style: "normal",
          _key: "582d726d46fd",
        },
      ],
      button: {
        label: "Stop Skewed Analytics",
        slug: {
          current: "/",
          _type: "slug",
        },
        mode: "light",
        externalLink: false,
        _type: "button",
        variant: "text-link-arrow",
      },
      heading: "Skewed analytics",
    },
    {
      subText: [
        {
          markDefs: [],
          children: [
            {
              _key: "af27a9cb93830",
              _type: "span",
              marks: [],
              text:
                "Identify and stop web scrapers that compromise your website.",
            },
          ],
          _type: "block",
          style: "normal",
          _key: "694a32435f8a",
        },
      ],
      button: {
        externalLink: false,
        _type: "button",
        variant: "text-link-arrow",
        label: "Stop Web Scraping",
        slug: {
          current: "/",
          _type: "slug",
        },
        mode: "light",
      },
      heading: "Web scraping",
      _type: "featuredCardsObject",
      icon: {
        _updatedAt: "2024-01-25T15:26:28Z",
        uploadId: "sYIDRFgmien7hcZyH7fTA9yJSFAp8qv7",
        mimeType: "image/svg+xml",
        extension: "svg",
        _rev: "L7VDs79nOp3hJw51jO6Jo1",
        originalFilename: "square-badge.svg",
        path:
          "images/uiptp553/production/0311a35269cb9bd62890a703fd063eda149ba271-48x49.svg",
        assetId: "0311a35269cb9bd62890a703fd063eda149ba271",
        _id: "image-0311a35269cb9bd62890a703fd063eda149ba271-48x49-svg",
        metadata: {
          isOpaque: false,
          blurHash: "ei27^sflf5fmkbfkfPfRfRfPfmfkkZf5acfmfRf5f5fRkvfRabf6f5",
          _type: "sanity.imageMetadata",
          palette: {
            lightMuted: {
              background: "#1c367c",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0,
            },
            vibrant: {
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.09,
              background: "#2c54c0",
            },
            dominant: {
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
              title: "#fff",
              population: 0.55,
              background: "#07147a",
            },
            _type: "sanity.imagePalette",
            darkMuted: {
              foreground: "#fff",
              title: "#fff",
              population: 0.17,
              background: "#242a46",
              _type: "sanity.imagePaletteSwatch",
            },
            muted: {
              foreground: "#fff",
              title: "#fff",
              population: 0.13,
              background: "#546199",
              _type: "sanity.imagePaletteSwatch",
            },
            lightVibrant: {
              background: "#93a9e6",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#000",
              title: "#fff",
              population: 0,
            },
            darkVibrant: {
              title: "#fff",
              population: 0.55,
              background: "#07147a",
              _type: "sanity.imagePaletteSwatch",
              foreground: "#fff",
            },
          },
          hasAlpha: true,
          lqip:
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAACJklEQVQ4jaWU3U4UQRCFe0RBRFgSf2IkuqcS1Cj+oULiDUEDCbgQY1avNBoTvaJPe+29z+Eb+SBe2WfwAUxND8smYNjVi5Oumen6pqq6qgOod6DWQN0DtQTq7phaan2d8TaAegVqoUtNgZpudXZETbta3wVnOXAHVAdUwJ78eTztDWxn7ASjeqDmLdX+shobSFWt77wl9QJY95DqDugv68oo/0mzuVmT23VA+jWAGHOwLz/D9rcfjU/53jAc2ETYsaRgqQAP/95sDOB+ALNHf6ZVdf3719CN+8GSRzhIueeQnrHu4GjK7jgLaq6VF/0hqAegLiNpos2mMtbBGc46Bpg9mglQ17wVrLTDqlFbRn0E9QHUUyTNDGrIk4GToB4Z9d6o10ZtGvUG1GdQn5D0DElzpb46ARhzQMyTxrxsVN+oDaPug3qMlJ8j5S0kLYM61wCTKvc9FtjUowCnjPkOqE1Q66BugbqIlC+Bum2u6E1dl1P+G7CEn70tphB1ANxoa3jTqCsWtWRRyxZ1fiQgSqG9hu64bVHPLea1VqsWtW5RKxYPDwUjAE+BumoxPymQZl1pbY/WrLRVOAIcNDaP9OFpi3nGYp5rNTtYqckyAHl49EpjI6mH1AJTXXWHJsUP6Di1rRW6Tb199IYnhSXl/74cko9vSXnXbwr/uMjfY19fi2ng44xdN/qgboC60PRakdujaHi/M/oHwJegXoDa/ke5rzP6fwDCM3xmh6huxgAAAABJRU5ErkJggg==",
          dimensions: {
            aspectRatio: 0.9795918367346939,
            height: 49,
            _type: "sanity.imageDimensions",
            width: 48,
          },
        },
        _type: "sanity.imageAsset",
        sha1hash: "0311a35269cb9bd62890a703fd063eda149ba271",
        size: 1293,
        _createdAt: "2024-01-25T15:26:28Z",
        url:
          "https://cdn.sanity.io/images/uiptp553/production/0311a35269cb9bd62890a703fd063eda149ba271-48x49.svg",
      },
      _key: "cfcaa881446a",
    },
  ],
  _rev: "J6m3sXezoblUkfhFapV9kT",
  sliderCards: null,
  _createdAt: "2024-01-25T13:54:03Z",
  _type: "featureSection",
  _id: "edcd7b08-f5ce-44ef-8828-d53481861268",
  logo: null,
  statsCards: null,
  productCards: null,
  button: {
    label: "View all products",
    slug: {
      current: "/",
      _type: "slug",
    },
    mode: "light",
    externalLink: false,
    _type: "button",
    variant: "secondary-arrow",
  },
  heading: "Tackle automated attacks you face every day and win against",
  identifier: "Featured Card Section",
  _updatedAt: "2024-01-25T15:26:55Z",
  cards: null,
  backPattern: null,
  backVector: null,
};
