export const mocks = {
  backPattern: {
    uploadId: '2vpJoNSPH8J8whpYUyeBMWUd0oP2Oha7',
    mimeType: 'image/svg+xml',
    _createdAt: '2024-01-25T08:19:34Z',
    _type: 'sanity.imageAsset',
    _updatedAt: '2024-01-25T08:19:34Z',
    url: 'https://cdn.sanity.io/images/uiptp553/production/67363536856a0186c78ceeded1952a3e7e64d2d3-942x391.svg',
    path: 'images/uiptp553/production/67363536856a0186c78ceeded1952a3e7e64d2d3-942x391.svg',
    extension: 'svg',
    _id: 'image-67363536856a0186c78ceeded1952a3e7e64d2d3-942x391-svg',
    sha1hash: '67363536856a0186c78ceeded1952a3e7e64d2d3',
    assetId: '67363536856a0186c78ceeded1952a3e7e64d2d3',
    originalFilename: 'Vector.svg',
    size: 60735,
    metadata: {
      hasAlpha: true,
      lqip: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAICAYAAAD5nd/tAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA+0lEQVQokXWSwU7DQAxEF9qGQqClNKgUKAIqcQc0LXwYAsnmwA8jNBZ35OAmq0APT7YSe8a73gRhalBLT+/fnvchPIHwGmpLqN1AzfMF1OZQm0KthFrfex5fvhqNVqxlF8IJhLcQ3kW8gvASwgsIzyE8g7KCcgSxAmI72wT9RwnhAsJlCLnAvBYRzjqcQjiGcM97129/BQcQVjHJLI49iZgzjboq8qPoTd3phhAeh2vZ4TDw5lHUjLP6fb+uWmzVivoyiogb3Nnx7340x41d4CAz83yQnoXpXu2/5eSTO74spxdszHKj4nfCj89G4OG1fjb51AkabDdqTH4AlcMLXRdW/FcAAAAASUVORK5CYII=',
      dimensions: {
        _type: 'sanity.imageDimensions',
        width: 942,
        aspectRatio: 2.4092071611253196,
        height: 391,
      },
      isOpaque: false,
      blurHash: 'MD57W~QkL}acVUa$p3VBkEa{Q*aHf-o*p2',
      _type: 'sanity.imageMetadata',
      palette: {
        vibrant: {
          title: '#fff',
          population: 0.04,
          background: '#32417d',
          _type: 'sanity.imagePaletteSwatch',
          foreground: '#fff',
        },
        dominant: {
          background: '#35385b',
          _type: 'sanity.imagePaletteSwatch',
          foreground: '#fff',
          title: '#fff',
          population: 0.4,
        },
        _type: 'sanity.imagePalette',
        darkMuted: {
          foreground: '#fff',
          title: '#fff',
          population: 0.4,
          background: '#35385b',
          _type: 'sanity.imagePaletteSwatch',
        },
        muted: {
          population: 0.05,
          background: '#405674',
          _type: 'sanity.imagePaletteSwatch',
          foreground: '#fff',
          title: '#fff',
        },
        lightVibrant: {
          population: 0,
          background: '#a0abd9',
          _type: 'sanity.imagePaletteSwatch',
          foreground: '#000',
          title: '#fff',
        },
        darkVibrant: {
          foreground: '#fff',
          title: '#fff',
          population: 0.16,
          background: '#092350',
          _type: 'sanity.imagePaletteSwatch',
        },
        lightMuted: {
          _type: 'sanity.imagePaletteSwatch',
          foreground: '#fff',
          title: '#fff',
          population: 0,
          background: '#2b386d',
        },
      },
    },
    _rev: 'GspWPjs815p7KTxv1z1trQ',
  },
  heading: 'Edge-computed analysis stops attacks before they start',
  logo: {
    _createdAt: '2024-01-25T07:54:42Z',
    originalFilename: 'Icon.svg',
    mimeType: 'image/svg+xml',
    extension: 'svg',
    metadata: {
      palette: {
        dominant: {
          title: '#fff',
          population: 0.58,
          background: '#444444',
          _type: 'sanity.imagePaletteSwatch',
          foreground: '#fff',
        },
        _type: 'sanity.imagePalette',
        darkMuted: {
          background: '#444444',
          _type: 'sanity.imagePaletteSwatch',
          foreground: '#fff',
          title: '#fff',
          population: 0.58,
        },
        muted: {
          foreground: '#fff',
          title: '#fff',
          population: 0.09,
          background: '#7c7c7c',
          _type: 'sanity.imagePaletteSwatch',
        },
        lightVibrant: {
          title: '#fff',
          population: 0,
          background: '#bcbcbc',
          _type: 'sanity.imagePaletteSwatch',
          foreground: '#000',
        },
        darkVibrant: {
          foreground: '#fff',
          title: '#fff',
          population: 0,
          background: '#424242',
          _type: 'sanity.imagePaletteSwatch',
        },
        lightMuted: {
          _type: 'sanity.imagePaletteSwatch',
          foreground: '#000',
          title: '#fff',
          population: 0.08,
          background: '#bcbcbc',
        },
        vibrant: {
          title: '#fff',
          population: 0,
          background: '#7f7f7f',
          _type: 'sanity.imagePaletteSwatch',
          foreground: '#fff',
        },
      },
      hasAlpha: true,
      lqip: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAXCAYAAAALHW+jAAAACXBIWXMAAAsTAAALEwEAmpwYAAACI0lEQVQ4jZWVz4vMYRzHZ3eNNVoc/EjbzkrJrvaCRCTlV62TsBdFzEpuHHBwk1IOyo8ornJBym0jF0WWdeLAn+APcH699IzPjGe/vt+xO/WpmXnm+3ren/fn/TxTU0+qu4EVaq1Yi36p29RDwAQwWAbNC+i5VlOXq1sTVN2kLvkftFfV4s0qdad6QG2q/QtRVAnkz0Nr1L3qpLpL3ag2Kh5cqo6qW9TVal9RYap+YFidUu+oN9U9Fb6uVS+ot8Oqehkw1YA6od5SP6h3w9+2r0BbCZDU3VM/qmfVZflQipNKfh5XXwCz6vUYVtdXdYP6UJ1TpxMwwbrAzof48Tr1FJAUvFXfAZfU4cyrBHygflZbHYXzWu4Ao50bwHP1vjqjvlHPxABy4FwCAn+BEe68muHde+CyejGUvlKPRm5Hs5Zb8xSWAEfC8NTOeXUcuAqkIT0F9qljQFsh0BsIjITCT+o5dQgYi8nPhg3H1Mex6fRCFObARsQpnaRHEacn6mvgS6nCwvHqAoE2MNYT+GC0/V39qX6LHDb+UZhNuUxhZ7OVkdEZ4Jf6I00faPTysJkNJQd2MpjOfCv8/FqpMKv16jXgmXoi9ycDpy6uqC/V00lh96SUAFPOdqhH4silgdRKoONxQUxlgS8F9sXtMQgMFI5lXvWATgLpAmm3XQYsetprPV1t6XY6HPB6JbAKlKWh892Quj0itXmxf2hVGyUP96dI/Qa50z7DP8cmfAAAAABJRU5ErkJggg==',
      dimensions: {
        _type: 'sanity.imageDimensions',
        width: 75,
        aspectRatio: 0.8522727272727273,
        height: 88,
      },
      isOpaque: false,
      blurHash: 'eRH2crIU9FM{00j[?boft7t700xu~qj[?bfQt7of-;Rjj[WBRjxu?b',
      _type: 'sanity.imageMetadata',
    },
    assetId: '2dc16a77df830c2c0c9bc160f2edcd88748f35fd',
    _type: 'sanity.imageAsset',
    path: 'images/uiptp553/production/2dc16a77df830c2c0c9bc160f2edcd88748f35fd-75x88.svg',
    url: 'https://cdn.sanity.io/images/uiptp553/production/2dc16a77df830c2c0c9bc160f2edcd88748f35fd-75x88.svg',
    size: 556,
    sha1hash: '2dc16a77df830c2c0c9bc160f2edcd88748f35fd',
    uploadId: 'LNWMx2UE3aVUS89cTjgD38Yj9APhWz71',
    _id: 'image-2dc16a77df830c2c0c9bc160f2edcd88748f35fd-75x88-svg',
    _updatedAt: '2024-01-25T07:54:42Z',
    _rev: 'J6m3sXezoblUkfhFans1K3',
  },
  subText: [
    {
      _type: 'block',
      style: 'normal',
      _key: '547612c8c5e9',
      markDefs: [],
      children: [
        {
          _type: 'span',
          marks: [],
          text: 'Netacea puts you in control. Powered by massive threat datasets, a machine learning engine detects attacks inside vast traffic flows. All before they execute. All at scale. Across your entire web surface.',
          _key: '716f3b3c62df0',
        },
      ],
    },
  ],
  variant: 'dark',
  thead: ['Without Netacea', 'With Netacea'],
  tbody: [
    {
      withoutNetacea: 'Limited client-side detection',
      _type: 'list',
      _key: '84e54754000a',
      withNetacea:
        'Full attack surface visibility - spots 33x more using Intent Analytics',
    },
    {
      withoutNetacea: 'Slow, tedious and manually updated agents',
      _type: 'list',
      _key: '94483a2df9ae',
      withNetacea: 'Automated server side updates, your always ready',
    },
    {
      _type: 'list',
      _key: '206d5149f19a',
      withNetacea: 'Detects active attacks in real-time, instant mitigation',
      withoutNetacea: 'Bots can go undetected for 18 weeks',
    },
    {
      withoutNetacea: 'Often bypassed by simple bots',
      _type: 'list',
      _key: 'bf456c8baf15',
      withNetacea: 'Hard to detect, difficult to bypass',
    },
    {
      _key: 'a7e141069457',
      withNetacea: 'Ultra-low false positive rate (0.001%)',
      withoutNetacea: 'False positives traded for decreased detection',
      _type: 'list',
    },
    {
      withoutNetacea: 'Complex to deploy, expensive to maintain',
      _type: 'list',
      _key: '6cc199b75cd0',
      withNetacea: 'Fast no code integration, reduces costs',
    },
  ],
}
