export const mocks = {
  section: {
    heading: 'Agentless across all APIs, websites and applications',
    variant: 'dark',
    _createdAt: '2024-01-24T12:17:45Z',
    _type: 'netaceaDifference',
    _id: '69fa8646-bf93-4b3a-a6ec-bbc851e3ceba',
    cards: [
      {
        image: {
          path: 'images/uiptp553/production/a111844ed65a0d7641a6568d903ae466a180d572-48x49.svg',
          url: 'https://cdn.sanity.io/images/uiptp553/production/a111844ed65a0d7641a6568d903ae466a180d572-48x49.svg',
          _type: 'sanity.imageAsset',
          mimeType: 'image/svg+xml',
          extension: 'svg',
          uploadId: 'qfxS7H6NW7zgba0NbyhgLfc5FxWqxby7',
          _updatedAt: '2024-01-24T12:20:13Z',
          sha1hash: 'a111844ed65a0d7641a6568d903ae466a180d572',
          metadata: {
            _type: 'sanity.imageMetadata',
            palette: {
              darkVibrant: {
                title: '#fff',
                population: 0.17,
                background: '#344e08',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#fff',
              },
              lightMuted: {
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#000',
                title: '#000',
                population: 0.13,
                background: '#c4d4b4',
              },
              vibrant: {
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#000',
                title: '#fff',
                population: 0.17,
                background: '#a4c67a',
              },
              dominant: {
                background: '#465c32',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#fff',
                title: '#fff',
                population: 0.68,
              },
              _type: 'sanity.imagePalette',
              darkMuted: {
                background: '#465c32',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#fff',
                title: '#fff',
                population: 0.68,
              },
              muted: {
                population: 0.17,
                background: '#8cac64',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#000',
                title: '#fff',
              },
              lightVibrant: {
                background: '#bce19c',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#000',
                title: '#000',
                population: 0.26,
              },
            },
            hasAlpha: true,
            lqip: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAACMklEQVQ4jaWUy04UURCGq0GDxMsQUWK8a9QY8S5oNN6iC6MDMYSlrn0DdP4e8QF8Czdm+I/6Tq5d4fw9uMNUd80FnQRGF5XuPufUd+r2t1F4TeEhhSsUZilcHtFmw9cZr4zCEoVjFCYoTIbt2aFNhk0EY8mBCxRqFKz1E/49krX6Ps5YMBaoU5hKRe6L2ahACln4TqUCdUsqgTVfTMozyjdza2nVkhq+b6ndKK0ClOfs++YbSx1YKhwIY5HXWOR1P1QCq4PVbd82Gra63vLvXRT2UzhMYbqqV56xaNpaG/bRZiKrvJty3VKR11PUsNpsWlp/b1HokxRuUrhD4XZ0dDqpMUa9M3oGhWcFv9yz7APLsHs1zMcpHA/Q1QCfp3CXwg0KB9LGilFvez7bAfdS+TUKcwGeoXCCwjyFxxROsY2xflbYDoipcJ6j8lsUnlB4EGv3KVygsLvXZQ0FbhmbfRQc9ChqNx+pX4q0z1IY3ybCfBDo3T0XwOuR7mkK9yg8q2rqzWhWkzEMGLXLPv34YJ/bvSgvRoRz8fTUnwZ8PLVLUOZzORzoI1DA0gYsdcqIXadHKJyJTvv7UQoHS2AV2R/AnlK2NMXhLktLrlXvaBtZ2lzpKmOMRahIHsTAYJdKKVCrbqki7EN7wNLSL4dUAx2NMB/s9LdS8tr//hxSxSgjXIy5s6+d5si/ry+dUqbd2V30l2WX1Vol/kNh/r4TGzzv0lzuAl9SeEHh+T+a+zpj+TfU9GcYGfzxAwAAAABJRU5ErkJggg==',
            dimensions: {
              _type: 'sanity.imageDimensions',
              width: 48,
              aspectRatio: 0.9795918367346939,
              height: 49,
            },
            isOpaque: false,
            blurHash: 'elD27gkBV]oe%_oxj[afayj[oxf7yAfjRRkBafkBkBaf.hj[R8afWC',
          },
          _createdAt: '2024-01-24T12:20:13Z',
          size: 1288,
          _id: 'image-a111844ed65a0d7641a6568d903ae466a180d572-48x49-svg',
          originalFilename: 'square-badge.svg',
          assetId: 'a111844ed65a0d7641a6568d903ae466a180d572',
          _rev: 'J6m3sXezoblUkfhFafMDak',
        },
        heading: 'No blindspots. No complexity',
        _type: 'cardObject',
        _key: '7d9a96a4d679',
        subText: [
          {
            children: [
              {
                _key: '32e82e19be020',
                _type: 'span',
                marks: [],
                text: 'A single edge integration for simple management',
              },
            ],
            _type: 'block',
            style: 'normal',
            _key: '440d9f82411f',
            markDefs: [],
          },
        ],
      },
      {
        image: {
          assetId: '7189ec2654e8a453de0311b97096f9808298692e',
          sha1hash: '7189ec2654e8a453de0311b97096f9808298692e',
          uploadId: 'coVcM3SLI7oTd36HFLNDXjzpodWojCVl',
          extension: 'svg',
          url: 'https://cdn.sanity.io/images/uiptp553/production/7189ec2654e8a453de0311b97096f9808298692e-49x49.svg',
          _createdAt: '2024-01-24T12:22:12Z',
          _updatedAt: '2024-01-24T12:22:12Z',
          path: 'images/uiptp553/production/7189ec2654e8a453de0311b97096f9808298692e-49x49.svg',
          mimeType: 'image/svg+xml',
          size: 944,
          metadata: {
            isOpaque: false,
            blurHash: 'ejDLF=oxoxkB.hoxfjaffQf7oxayyAj[R8ayfQkBfQj@.hj@R8azaf',
            _type: 'sanity.imageMetadata',
            palette: {
              vibrant: {
                population: 0.04,
                background: '#547434',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#fff',
                title: '#fff',
              },
              dominant: {
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#fff',
                title: '#fff',
                population: 0.5,
                background: '#305008',
              },
              _type: 'sanity.imagePalette',
              darkMuted: {
                title: '#fff',
                population: 0.04,
                background: '#445434',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#fff',
              },
              muted: {
                title: '#fff',
                population: 0.04,
                background: '#84ac5c',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#000',
              },
              lightVibrant: {
                title: '#fff',
                population: 0.12,
                background: '#a9cc8e',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#000',
              },
              darkVibrant: {
                title: '#fff',
                population: 0.5,
                background: '#305008',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#fff',
              },
              lightMuted: {
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#000',
                title: '#fff',
                population: 0.29,
                background: '#b5cda6',
              },
            },
            hasAlpha: true,
            lqip: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAACRUlEQVQ4jaWUS08UQRSF74AiMbogGMWIz6BRUaNofOAjIW6MgOgfcMVCE0w0wdC3B4wxJvwK3bhw6tSE+Af8I25YSMSNyTB9GnwsNLeoAQmNgXFxMj1d1d+cO31OCagPooZBHWxSw6DeB/WORNgJUDv+Q52gngJ1RCJ9DzIVl6VNSMUxNU5XAzhkwGp9XJBp6e/NYFoq0hogy+IWEuPsB/WeeOqQDw4T8abFVFx90mC2FoQCVb6VxTMRfBkT//mR7evyBmw4NKDJ1ctSWQa2IE/bfJ62m7CqNlBbvI26qIK5x+JnRxsjrwcGB1naEu5Re0E966m9Pl7HP78DTEpgIu73tGB2NDjcGMh0O6gnQR0Atc9TT4N6DtR+UG+Degx50uryRNz3yU0BbSyDXAZ1X4zGUVAvgHoL1OMuT7YF4FJ5U8AdcbSLwQ31DKiX3LLLK6D2OG4N2BYd9kfozThyD6jXgkNuZeQsbQX1CKg3IqAv/oB9Xge121FLzl7Kzxf/BlocTKDuBPUwqOdBvRpHtetDoLZXqPKmlsrMx4GNgRZsC/R7S//ShDiqOd0dM2YvZ5dl0NUs8BNiscH8WDEwwLJEZn5MhW5Wf40L8uVWuPy5+OzZSkvezU2HtTDN/FhxsBtAc4jQ0dWaVWuvpcKXK9/DgRC6ruI/PRR8fbIKjF3uNNgHPhVXTwtkdSwXry1YdKbWdHkE1L1vl17ZhlIxcGNZ711mNdQDdsg2gNbR7nizGR2MCRg0oFWpcYQbvBnZs3etqn8AC8RoIvwb5UMAAAAASUVORK5CYII=',
            dimensions: {
              _type: 'sanity.imageDimensions',
              width: 49,
              aspectRatio: 1,
              height: 49,
            },
          },
          _rev: 'L7VDs79nOp3hJw51jI0HW5',
          originalFilename: 'square-badge.svg',
          _type: 'sanity.imageAsset',
          _id: 'image-7189ec2654e8a453de0311b97096f9808298692e-49x49-svg',
        },
        heading: 'Invisible protection. Costly to attack',
        _type: 'cardObject',
        _key: '71e9cb0f9449',
        subText: [
          {
            _type: 'block',
            style: 'normal',
            _key: '581811a7dcdd',
            markDefs: [],
            children: [
              {
                _type: 'span',
                marks: [],
                text: "Because there's no agent it's hard for bad actors to bypass.",
                _key: 'cc9897c01b3a0',
              },
            ],
          },
        ],
      },
      {
        subText: [
          {
            markDefs: [],
            children: [
              {
                marks: [],
                text: 'We give you granular real-time insight on attacks and a big picture view for risk strategy',
                _key: '631aef10553d0',
                _type: 'span',
              },
            ],
            _type: 'block',
            style: 'normal',
            _key: '59d45a3675d2',
          },
        ],
        image: {
          assetId: 'ebc531fea83afb11d5b1e249fb21eb460c5d8fce',
          _rev: 'J6m3sXezoblUkfhFafNwJX',
          path: 'images/uiptp553/production/ebc531fea83afb11d5b1e249fb21eb460c5d8fce-49x49.svg',
          size: 897,
          uploadId: '9c8RsvDpU030bvPKOiPFRDeH0Q6ctLpS',
          mimeType: 'image/svg+xml',
          _type: 'sanity.imageAsset',
          sha1hash: 'ebc531fea83afb11d5b1e249fb21eb460c5d8fce',
          extension: 'svg',
          _updatedAt: '2024-01-24T12:22:51Z',
          originalFilename: 'square-badge.svg',
          url: 'https://cdn.sanity.io/images/uiptp553/production/ebc531fea83afb11d5b1e249fb21eb460c5d8fce-49x49.svg',
          metadata: {
            dimensions: {
              height: 49,
              _type: 'sanity.imageDimensions',
              width: 49,
              aspectRatio: 1,
            },
            isOpaque: false,
            blurHash: 'enCbI.j[yAox%_kBj@f7afaztikBtPWCRRoeafayoxfj.hazM#kBaz',
            _type: 'sanity.imageMetadata',
            palette: {
              muted: {
                title: '#fff',
                population: 1.12,
                background: '#79995a',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#fff',
              },
              lightVibrant: {
                background: '#a9cc8e',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#000',
                title: '#fff',
                population: 0.12,
              },
              darkVibrant: {
                background: '#344c0a',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#fff',
                title: '#fff',
                population: 0.21,
              },
              lightMuted: {
                background: '#b9ccac',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#000',
                title: '#fff',
                population: 0.12,
              },
              vibrant: {
                population: 1.21,
                background: '#74a44d',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#fff',
                title: '#fff',
              },
              dominant: {
                title: '#fff',
                population: 3.33,
                background: '#3c4f2c',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#fff',
              },
              _type: 'sanity.imagePalette',
              darkMuted: {
                title: '#fff',
                population: 3.33,
                background: '#3c4f2c',
                _type: 'sanity.imagePaletteSwatch',
                foreground: '#fff',
              },
            },
            hasAlpha: true,
            lqip: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAACX0lEQVQ4jaWVvWsUURTF75pCRdSYRF0/AlaCih8IiqAEQQTRJGprY5NCNIqKMXNmF21s7PQPUAvB7LtvDJZW9pZWok0KIQnYmJkzu4VF5L6ZUQnZSGJxeHd34Dfn3jlzR5S4oMQVJUaUuLRGjShx1SRKXFbigBL9Smz7D+3/G1h3bIjLIC6LVy3NYJwBc2rFqBK73EIkBXTVsFqSPhBPDHhi2IpRT9T12w3R2VviGUnSgSSdOMhb3Z4U34mCknah8Lsdi8+ioNLhcOWw7mfGxM+N2w0kaTfk9vvhYgS0doq2fFD052w3RA22FBgczowFh27hoUx3mvJi/p60UkiLDdEcomkkSWpjCfMKZwX03YBu8ZloHhugpnm8UfN4k8vjdQY0VwZs2fUSqGXLXR26n4/F5TCtc+HJ46DLUVdisxK7ldipxHpH9DhGtWIUUXeHbxafy+vOhLTy0FqvI44ocUqJE0qcVeK0EoeUGHTEBs2jlYF+djy0Y+2ZA0f0OeK4EmeUOKbEkBLXlDivRK/SQCsAdW68nEccZlRCtyjRp4y3KnG0BJ7T8H/0D4cWmwzyijfFMZa36f0QI3OtedxTvp77lNhuc6wi41d0yEg+Zx+llU2EOsCqqGSoTWWRLH75INM/mpJ0eyhLg91ikbcpThZPvQq3Xcsgn74/lSRtiLaby8fGgDp/R/zX678zZm9JmGV5VrUBqxsuGxtftuw6jyQsiDReld7xbgEl+sNyKJfrHtsaray5aqBLUXvZeWKcHbYKrbCNaxkbDOC1aa8ShyvgSSUulk5t2a5F1Sdk6BfOOGOV09wzzwAAAABJRU5ErkJggg==',
          },
          _id: 'image-ebc531fea83afb11d5b1e249fb21eb460c5d8fce-49x49-svg',
          _createdAt: '2024-01-24T12:22:51Z',
        },
        heading: 'Track live attacks. Plan more effectively',
        _type: 'cardObject',
        _key: 'd55c153fe70f',
      },
    ],
    _rev: 'GspWPjs815p7KTxv1k4tSG',
    _updatedAt: '2024-01-24T12:57:28Z',
    button: {
      _type: 'button',
      variant: 'primary-arrow',
      label: 'Try Netacea',
      slug: {
        current: '#',
        _type: 'slug',
      },
      mode: 'dark',
      externalLink: false,
    },
    identifier: 'Netacea Difference',
  },
}
